name: Publish Manylinux

on:
  release:
    types: [ prereleased, released ]


jobs:    
  build:
    runs-on: ubuntu-latest
    env:
      KVXOPT_BUILD_GSL: 1
      KVXOPT_BUILD_FFTW: 1
      KVXOPT_BUILD_GLPK: 1
      KVXOPT_BUILD_DSDP: 0
      KVXOPT_LAPACK_LIB: openblas
      KVXOPT_BLAS_LIB: openblas
      KVXOPT_GLPK_INC_DIR: /usr/include/glpk
      KVXOPT_SUITESPARSE_INC_DIR: /usr/include/suitesparse
      KVXOPT_SUITESPARSE_CONFIG: 0

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine

      - name: Build manylinux1 Python wheels
        uses: RalfG/python-wheels-manylinux-build@v0.3.1-manylinux1_x86_64
        with:
          pre-build-command: 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/'
          python-versions: 'cp27-cp27m cp27-cp27mu cp35-cp35m cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39'
          build-requirements: ''
          system-packages: 'openblas-devel fftw-devel glpk-devel gsl-devel suitesparse-devel'

      - name: Build manylinux2010 Python wheels
        uses: RalfG/python-wheels-manylinux-build@v0.3.1-manylinux2010_x86_64
        with:
          pre-build-command: 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/'
          python-versions: 'cp27-cp27m cp27-cp27mu cp35-cp35m cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39'
          build-requirements: ''
          system-packages: 'openblas-devel fftw-devel glpk-devel gsl-devel suitesparse-devel'

      - name: Build manylinux2014 Python wheels
        uses: RalfG/python-wheels-manylinux-build@v0.3.1-manylinux2014_x86_64
        with:
          pre-build-command: 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/'
          python-versions: 'cp35-cp35m cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39'
          build-requirements: ''
          system-packages: 'openblas-devel fftw-devel glpk-devel gsl-devel suitesparse-devel'

      - uses: actions/upload-artifact@v2
        with:
          name: linux-wheels
          path: dist/*-manylinux*.whl

      - name: Publish wheels to PyPI test
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_TEST_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_PASSWORD }}
        run: |
          twine upload --repository testpypi dist/*-manylinux*.whl
        if: ${{ github.event_name == 'release' && github.event.action == 'prereleased' }}

      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*-manylinux*.whl
        if: ${{ github.event_name == 'release' && github.event.action == 'released' }}


      #- name: Publish wheels to PyPI
      #  env:
      #    TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      #    TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      #  run: |
      #    twine upload dist/*-manylinux*.whl